### ISSUE TITLE
How to run it?

### ISSUE THREAD

**Issue by nezvers** [tehskai/godot-unpacker#1]
I'm sorry, but I'm not that savvy with executing programs that are not *.exe.
How exactly it's supposed to run *.php file and where do I put execution commands?

**Comment by tehskai** [comment]
Hello,

I removed obsolete php script and replaced it with newer python version.
To run it you should have python 3 interpreter (https://www.python.org/downloads/) installed on your machine.
After installation script should be put in game directory. Then you open terminal (linux) or cmd (windows) navigate to game folder (cd c:\games\game) and run it like this:
```
python godot-unpacker.py data.pck
```
or if game is a self-contained executable
```
python godot-unpacker.py game.exe
```
All extracted files will be in "output" directory.

Hope this helps.
