### ISSUE TITLE
File paths have trailing \x00s

### ISSUE THREAD

**Issue by tankorsmash** [tehskai/godot-unpacker#2]
https://github.com/tehskai/godot-unpacker/blob/a33326a04290ff252b78952bfc19d8b089c73cb8/godot-unpacker.py#L63

Not sure what the cause is, but I had several \x00's at the end of my paths and adding an `rstrip` allowed me to unpack properly:

     file_name_full.rstrip('\x00')

**Comment by alex-evelyn** [comment]
Same. I used `with open(os.path.join(path, file_name_full.rstrip("\0")), "w+b") as p:`.

Please fix this.
